choices_state=[
    'Germany',
    'Baden-Wuerttemberg',
    'Bayern',
    'Berlin',
    'Brandenburg',
    'Bremen',
    'Hamburg',
    'Hessen',
    'Mecklenburg-Vorpommern',
    'Niedersachsen',
    'Nordrhein-Westfalen',
    'Rheinland-Pfalz',
    'Saarland',
    'Sachsen',
    'Sachsen-Anhalt',
    'Schleswig-Holstein',
    'Thueringen'
]
choices_county=[
    '',
    'LK Alb-Donau-Kreis',
    'LK Biberach',
    'LK Boeblingen','LK Bodenseekreis',
    'LK Breisgau-Hochschwarzwald',
    'LK Calw',
    'LK Emmendingen',
    'LK Enzkreis',
    'LK Esslingen',
    'LK Freudenstadt',
    'LK Goeppingen',
    'LK Heidenheim',
    'LK Heilbronn',
    'LK Hohenlohekreis',
    'LK Karlsruhe',
    'LK Konstanz',
    'LK Loerrach',
    'LK Ludwigsburg',
    'LK Main-Tauber-Kreis',
    'LK Neckar-Odenwald-Kreis',
    'LK Ortenaukreis',
    'LK Ostalbkreis',
    'LK Rastatt',
    'LK Ravensburg',
    'LK Rems-Murr-Kreis',
    'LK Reutlingen',
    'LK Rhein-Neckar-Kreis',
    'LK Rottweil',
    'LK Schwaebisch Hall',
    'LK Schwarzwald-Baar-Kreis',
    'LK Sigmaringen',
    'LK Tuebingen',
    'LK Tuttlingen',
    'LK Waldshut',
    'LK Zollernalbkreis',
    'SK Baden-Baden',
    'SK Freiburg i.Breisgau',
    'SK Heidelberg',
    'SK Heilbronn',
    'SK Karlsruhe',
    'SK Mannheim',
    'SK Pforzheim',
    'SK Stuttgart',
    'SK Ulm',
    'LK Aichach-Friedberg',
    'LK Altoetting',
    'LK Amberg-Sulzbach',
    'LK Ansbach',
    'LK Aschaffenburg',
    'LK Augsburg',
    'LK Bad Kissingen',
    'LK Bad Toelz-Wolfratshausen',
    'LK Bamberg',
    'LK Bayreuth',
    'LK Berchtesgadener Land',
    'LK Cham',
    'LK Coburg',
    'LK Dachau',
    'LK Deggendorf',
    'LK Dillingen a.d.Donau',
    'LK Dingolfing-Landau',
    'LK Donau-Ries',
    'LK Ebersberg',
    'LK Eichstaett',
    'LK Erding',
    'LK Erlangen-Hoechstadt',
    'LK Forchheim',
    'LK Freising',
    'LK Freyung-Grafenau',
    'LK Fuerstenfeldbruck',
    'LK Fuerth',
    'LK Garmisch-Partenkirchen',
    'LK Guenzburg',
    'LK Hassberge',
    'LK Hof',
    'LK Kelheim',
    'LK Kitzingen',
    'LK Kronach',
    'LK Kulmbach',
    'LK Landsberg a.Lech',
    'LK Landshut',
    'LK Lichtenfels',
    'LK Lindau',
    'LK Main-Spessart',
    'LK Miesbach',
    'LK Miltenberg',
    'LK Muehldorf a.Inn',
    'LK Muenchen',
    'LK Neu-Ulm',
    'LK Neuburg-Schrobenhausen',
    'LK Neumarkt i.d.OPf.',
    'LK Neustadt a.d.Aisch-Bad Windsheim',
    'LK Neustadt a.d.Waldnaab',
    'LK Nuernberger Land',
    'LK Oberallgaeu',
    'LK Ostallgaeu',
    'LK Passau',
    'LK Pfaffenhofen a.d.Ilm',
    'LK Regen',
    'LK Regensburg',
    'LK Rhoen-Grabfeld',
    'LK Rosenheim',
    'LK Roth',
    'LK Rottal-Inn',
    'LK Schwandorf',
    'LK Schweinfurt',
    'LK Starnberg',
    'LK Straubing-Bogen',
    'LK Tirschenreuth',
    'LK Traunstein',
    'LK Unterallgaeu',
    'LK Weilheim-Schongau',
    'LK Weissenburg-Gunzenhausen',
    'LK Wunsiedel i.Fichtelgebirge',
    'LK Wuerzburg',
    'SK Amberg',
    'SK Ansbach',
    'SK Aschaffenburg',
    'SK Augsburg',
    'SK Bamberg',
    'SK Bayreuth',
    'SK Coburg',
    'SK Erlangen',
    'SK Fuerth',
    'SK Hof',
    'SK Ingolstadt',
    'SK Kaufbeuren',
    'SK Kempten',
    'SK Landshut',
    'SK Memmingen',
    'SK Muenchen',
    'SK Nuernberg',
    'SK Passau',
    'SK Regensburg',
    'SK Rosenheim',
    'SK Schwabach',
    'SK Schweinfurt',
    'SK Straubing',
    'SK Weiden i.d.OPf.',
    'SK Wuerzburg',
    'SK Berlin Charlottenburg-Wilmersdorf',
    'SK Berlin Friedrichshain-Kreuzberg',
    'SK Berlin Lichtenberg',
    'SK Berlin Marzahn-Hellersdorf',
    'SK Berlin Mitte',
    'SK Berlin Neukoelln',
    'SK Berlin Pankow',
    'SK Berlin Reinickendorf',
    'SK Berlin Spandau',
    'SK Berlin Steglitz-Zehlendorf',
    'SK Berlin Tempelhof-Schoeneberg',
    'SK Berlin Treptow-Koepenick',
    'LK Barnim',
    'LK Dahme-Spreewald',
    'LK Elbe-Elster',
    'LK Havelland',
    'LK Maerkisch-Oderland',
    'LK Oberhavel',
    'LK Oberspreewald-Lausitz',
    'LK Oder-Spree',
    'LK Ostprignitz-Ruppin',
    'LK Potsdam-Mittelmark',
    'LK Prignitz',
    'LK Spree-Neisse',
    'LK Teltow-Flaeming',
    'LK Uckermark',
    'SK Brandenburg a.d.Havel',
    'SK Cottbus',
    'SK Frankfurt ',
    'SK Potsdam',
    'SK Bremen',
    'SK Bremerhaven',
    'SK Hamburg',
    'LK Bergstrasse',
    'LK Darmstadt-Dieburg',
    'LK Fulda',
    'LK Giessen',
    'LK Gross-Gerau',
    'LK Hersfeld-Rotenburg',
    'LK Hochtaunuskreis',
    'LK Kassel',
    'LK Lahn-Dill-Kreis',
    'LK Limburg-Weilburg',
    'LK Main-Kinzig-Kreis',
    'LK Main-Taunus-Kreis',
    'LK Marburg-Biedenkopf',
    'LK Odenwaldkreis',
    'LK Offenbach',
    'LK Rheingau-Taunus-Kreis',
    'LK Schwalm-Eder-Kreis',
    'LK Vogelsbergkreis',
    'LK Waldeck-Frankenberg',
    'LK Werra-Meissner-Kreis',
    'LK Wetteraukreis',
    'SK Darmstadt',
    'SK Frankfurt am Main',
    'SK Kassel',
    'SK Offenbach',
    'SK Wiesbaden',
    'LK Ludwigslust-Parchim',
    'LK Mecklenburgische Seenplatte',
    'LK Nordwestmecklenburg',
    'LK Rostock',
    'LK Vorpommern-Greifswald',
    'LK Vorpommern-Ruegen',
    'SK Rostock',
    'SK Schwerin',
    'LK Ammerland',
    'LK Aurich',
    'LK Celle',
    'LK Cloppenburg',
    'LK Cuxhaven',
    'LK Diepholz',
    'LK Emsland',
    'LK Friesland',
    'LK Gifhorn',
    'LK Goslar',
    'LK Goettingen',
    'LK Grafschaft Bentheim',
    'LK Hameln-Pyrmont',
    'LK Harburg',
    'LK Heidekreis',
    'LK Helmstedt',
    'LK Hildesheim',
    'LK Holzminden',
    'LK Leer',
    'LK Luechow-Dannenberg',
    'LK Lueneburg',
    'LK Nienburg',
    'LK Northeim',
    'LK Oldenburg',
    'LK Osnabrueck',
    'LK Osterholz',
    'LK Peine',
    'LK Rotenburg',
    'LK Schaumburg',
    'LK Stade',
    'LK Uelzen',
    'LK Vechta',
    'LK Verden',
    'LK Wesermarsch',
    'LK Wittmund',
    'LK Wolfenbuettel',
    'Region Hannover',
    'SK Braunschweig',
    'SK Delmenhorst',
    'SK Emden',
    'SK Oldenburg',
    'SK Osnabrueck',
    'SK Salzgitter',
    'SK Wilhelmshaven',
    'SK Wolfsburg',
    'LK Borken',
    'LK Coesfeld',
    'LK Dueren',
    'LK Ennepe-Ruhr-Kreis',
    'LK Euskirchen',
    'LK Guetersloh',
    'LK Heinsberg',
    'LK Herford',
    'LK Hochsauerlandkreis',
    'LK Hoexter',
    'LK Kleve',
    'LK Lippe',
    'LK Maerkischer Kreis',
    'LK Mettmann',
    'LK Minden-Luebbecke',
    'LK Oberbergischer Kreis',
    'LK Olpe',
    'LK Paderborn',
    'LK Recklinghausen',
    'LK Rhein-Erft-Kreis',
    'LK Rhein-Kreis Neuss',
    'LK Rhein-Sieg-Kreis',
    'LK Rheinisch-Bergischer Kreis',
    'LK Siegen-Wittgenstein',
    'LK Soest',
    'LK Steinfurt',
    'LK Unna',
    'LK Viersen',
    'LK Warendorf',
    'LK Wesel',
    'SK Bielefeld',
    'SK Bochum',
    'SK Bonn',
    'SK Bottrop',
    'SK Dortmund',
    'SK Duisburg',
    'SK Duesseldorf',
    'SK Essen',
    'SK Gelsenkirchen',
    'SK Hagen',
    'SK Hamm',
    'SK Herne',
    'SK Koeln',
    'SK Krefeld',
    'SK Leverkusen',
    'SK Moenchengladbach',
    'SK Muelheim a.d.Ruhr',
    'SK Muenster',
    'SK Oberhausen',
    'SK Remscheid',
    'SK Solingen',
    'SK Wuppertal',
    'StadtRegion Aachen',
    'LK Ahrweiler',
    'LK Altenkirchen',
    'LK Alzey-Worms',
    'LK Bad Duerkheim',
    'LK Bad Kreuznach',
    'LK Bernkastel-Wittlich',
    'LK Birkenfeld',
    'LK Bitburg-Pruem',
    'LK Cochem-Zell',
    'LK Donnersbergkreis',
    'LK Germersheim',
    'LK Kaiserslautern',
    'LK Kusel',
    'LK Mainz-Bingen',
    'LK Mayen-Koblenz',
    'LK Neuwied',
    'LK Rhein-Hunsrueck-Kreis',
    'LK Rhein-Lahn-Kreis',
    'LK Rhein-Pfalz-Kreis',
    'LK Suedliche Weinstrasse',
    'LK Suedwestpfalz',
    'LK Trier-Saarburg',
    'LK Vulkaneifel',
    'LK Westerwaldkreis',
    'SK Frankenthal',
    'SK Kaiserslautern',
    'SK Koblenz',
    'SK Landau i.d.Pfalz',
    'SK Ludwigshafen',
    'SK Mainz',
    'SK Neustadt a.d.Weinstrasse',
    'SK Pirmasens',
    'SK Speyer',
    'SK Trier',
    'SK Worms',
    'SK Zweibruecken',
    'LK Merzig-Wadern',
    'LK Neunkirchen',
    'LK Saarlouis',
    'LK Saarpfalz-Kreis',
    'LK Sankt Wendel',
    'LK Stadtverband Saarbruecken',
    'LK Bautzen',
    'LK Erzgebirgskreis',
    'LK Goerlitz',
    'LK Leipzig',
    'LK Meissen',
    'LK Mittelsachsen',
    'LK Nordsachsen',
    'LK Saechsische Schweiz-Osterzgebirge',
    'LK Vogtlandkreis',
    'LK Zwickau',
    'SK Chemnitz',
    'SK Dresden',
    'SK Leipzig',
    'LK Altmarkkreis Salzwedel',
    'LK Anhalt-Bitterfeld',
    'LK Boerde',
    'LK Burgenlandkreis',
    'LK Harz',
    'LK Jerichower Land',
    'LK Mansfeld-Suedharz',
    'LK Saalekreis',
    'LK Salzlandkreis',
    'LK Stendal',
    'LK Wittenberg',
    'SK Dessau-Rosslau',
    'SK Halle',
    'SK Magdeburg',
    'LK Dithmarschen',
    'LK Herzogtum Lauenburg',
    'LK Nordfriesland',
    'LK Ostholstein',
    'LK Pinneberg',
    'LK Ploen',
    'LK Rendsburg-Eckernfoerde',
    'LK Schleswig-Flensburg',
    'LK Segeberg',
    'LK Steinburg',
    'LK Stormarn',
    'SK Flensburg',
    'SK Kiel',
    'SK Luebeck',
    'SK Neumuenster',
    'LK Altenburger Land',
    'LK Eichsfeld',
    'LK Gotha',
    'LK Greiz',
    'LK Hildburghausen',
    'LK Ilm-Kreis',
    'LK Kyffhaeuserkreis',
    'LK Nordhausen',
    'LK Saale-Holzland-Kreis',
    'LK Saale-Orla-Kreis',
    'LK Saalfeld-Rudolstadt',
    'LK Schmalkalden-Meiningen',
    'LK Soemmerda',
    'LK Sonneberg',
    'LK Unstrut-Hainich-Kreis',
    'LK Wartburgkreis',
    'LK Weimarer Land',
    'SK Eisenach',
    'SK Erfurt',
    'SK Gera',
    'SK Jena',
    'SK Suhl',
    'SK Weimar'
]