import pandas as pd

# TODO: Pandas df for easier handeling
ARS = {'Nordrhein-Westfalen': ['Jena', 'Bielefeld', 'Bochum', 'Bonn', 'Borken',
       'Bottrop', 'Cösfeld', 'Dortmund', 'Duisburg',
       'Düren', 'Düsseldorf', 'Ennepe-Ruhr-Kreis', 'Essen',
       'Eurchen', 'Gelsenkirchen', 'Gütersloh', 'Hagen',
       'Hamm', 'Heinsberg', 'Herford', 'Herne',
       'Hochsaürlandkreis', 'Höxter', 'Kleve', 'Krefeld',
       'Ulm', 'Leverkusen', 'Lippe', 'Mettmann',
       'Minden-Lübbecke', 'Märkischer Kreis',
       'Mönchengladbach', 'Mülheim a.d.Ruhr', 'Leer',
       'Oberbergischer Kreis', 'Oberhausen', 'Olpe',
       'Paderborn', 'Recklinghausen', 'Remscheid',
       'Rhein-Erft-Kreis', 'Rhein-Kreis Neuss',
       'Rhein-Sieg-Kreis', 'Rheinisch-Bergischer Kreis',
       'Siegen-Wittgenstein', 'Söst', 'Solingen',
       'Steinfurt', 'Unna', 'Viersen', 'Warendorf',
       'Wesel', 'Wuppertal'], 'Rheinland-Pfalz': ['Ahrweiler', 'Altenkirchen', 'Alzey-Worms',
       'Bad Dürkheim', 'Bad Kreuznach', 'Bernkastel-Wittlich',
       'Birkenfeld', 'Cochem-Zell', 'Donnersbergkreis',
       'Bitburg-Prüm', 'Frankenthal', 'Germersheim',
       'Kaiserslautern', 'Kaiserslautern', 'Koblenz', 'Kusel',
       'Landau i.d.Pfalz', 'Ludwigshafen', 'Mainz',
       'Mainz-Bingen', 'Mayen-Koblenz',
       'Neustadt a.d.Weinstrasse', 'Neuwied', 'Pirmasens',
       'Rhein-Hunsrück-Kreis', 'Rhein-Lahn-Kreis',
       'Rhein-Pfalz-Kreis', 'Speyer', 'Südliche Weinstrasse',
       'Südwestpfalz', 'Trier', 'Trier-Saarburg',
       'Vuneifel', 'Westerwaldkreis', 'Worms',
       'Zweibrücken'], 'Bayern': ['Aichach-Friedberg', 'Altötting', 'Amberg',
       'Amberg-Sulzbach', 'Ansbach', 'Ansbach',
       'Aschaffenburg', 'Aschaffenburg', 'Augsburg',
       'Augsburg', 'Bad Kissingen', 'Bad Tölz-Wolfratshausen',
       'Bamberg', 'Bamberg', 'Bayreuth', 'Bayreuth',
       'Berchtesgadener Land', 'Cham', 'Coburg', 'Coburg',
       'Dachau', 'Deggendorf', 'Dillingen a.d.Donau',
       'Dingolfing-Landau', 'Donau-Ries', 'Ebersberg',
       'Eichstätt', 'Erding', 'Erlangen',
       'Erlangen-Höchstadt', 'Forchheim', 'Freising',
       'Freyung-Grafenau', 'Fürstenfeldbruck', 'Fürth',
       'Fürth', 'Garmisch-Partenkirchen', 'Coburg',
       'Hassberge', 'Hof', 'Hof', 'Ingolstadt',
       'Kaufbeuren', 'Kelheim', 'Unterallgäu', 'Kitzingen',
       'Kronach', 'Kulmbach', 'Landsberg a.Lech', 'Landshut',
       'Landshut', 'Lichtenfels', 'Bodenseekreis',
       'Main-Spessart', 'Memmingen', 'Miesbach', 'Miltenberg',
       'Mühldorf a.Inn', 'München', 'München', 'Neu-Ulm',
       'Neuburg-Schrobenhausen', 'Neumarkt i.d.OPf.',
       'Neustadt a.d.Aisch-Bad Windsheim', 'Neustadt a.d.Waldnaab',
       'Amberg', 'Nürnberger Land', 'Oberallgäu',
       'Ostallgäu', 'Passau', 'Passau',
       'Pfaffenhofen a.d.Ilm', 'Regen', 'Regensburg',
       'Regensburg', 'Rhön-Grabfeld', 'Rosenheim',
       'Rosenheim', 'Roth', 'Rottal-Inn', 'Schwabach',
       'Schwandorf', 'Schweinfurt', 'Schweinfurt',
       'Starnberg', 'Straubing', 'Straubing-Bogen',
       'Tirschenreuth', 'Traunstein', 'Unterallgäu',
       'Weiden i.d.OPf.', 'Weilheim-Schongau',
       'Weissenburg-Gunzenhausen', 'Wunsiedel i.Fichtelgebirge',
       'Coburg', 'Coburg'], 'Baden-Württemberg': ['Alb-Donau-Kreis', 'Baden-Baden', 'Biberach',
       'Bodenseekreis', 'Breisgau-Hochschwarzwald', 'Böblingen',
       'Calw', 'Emmendingen', 'Enzkreis', 'Esslingen',
       'Freiburg i.Breisgau', 'Freudenstadt', 'Göppingen',
       'Heidelberg', 'Heidenheim', 'Heilbronn', 'Heilbronn',
       'Hohenlohekreis', 'Karlsruhe', 'Karlsruhe', 'Konstanz',
       'Ludwigsburg', 'Aurich', 'Main-Tauber-Kreis',
       'Mannheim', 'Neckar-Odenwald-Kreis', 'Ortenaukreis',
       'Ostalbkreis', 'Pforzheim', 'Rastatt', 'Ravensburg',
       'Rems-Murr-Kreis', 'Reutlingen', 'Rhein-Neckar-Kreis',
       'Rottweil', 'Schwarzwald-Baar-Kreis', 'Schwäbisch Hall',
       'Sigmaringen', 'Stuttgart', 'Tuttlingen', 'Regen',
       'Ulm', 'Waldshut', 'Zollernalbkreis'], 'Thüringen': ['Altenburger Land', 'Eichsfeld', 'Eisenach', 'Erfurt',
       'Gera', 'Gotha', 'Greiz', 'Hildburghausen',
       'Ilm-Kreis', 'Jena', 'Kyffhäuserkreis', 'Nordhausen',
       'Saale-Holzland-Kreis', 'Saale-Orla-Kreis',
       'Saalfeld-Rudolstadt', 'Schmalden-Meiningen',
       'Sonneberg', 'Suhl', 'Gera', 'Unstrut-Hainich-Kreis',
       'Wartburgkreis', 'Weimar', 'Weimarer Land'], 'Sachsen-Anhalt': ['Altmarkkreis Salzwedel', 'Anhalt-Bitterfeld',
       'Burgenlandkreis', 'Börde', 'Dessau-Rosslau', 'Stade',
       'Harz', 'Jerichower Land', 'Magdeburg',
       'Mansfeld-Südharz', 'Saalekreis', 'Salzlandkreis',
       'Stendal', 'Wittenberg'], 'Niedersachsen': ['Ammerland', 'Aurich', 'Braunschweig', 'Celle',
       'Cloppenburg', 'Cuxhaven', 'Delmenhorst', 'Diepholz',
       'Emden', 'Emsland', 'Friesland', 'Gifhorn',
       'Goslar', 'Grafschaft Bentheim', 'Göttingen',
       'Hameln-Pyrmont', 'Harburg', 'Heidekreis', 'Helmstedt',
       'Hildesheim', 'Holzminden', 'Leer',
       'Lüchow-Dannenberg', 'Coburg', 'Nienburg', 'Northeim',
       'Oldenburg', 'Oldenburg', 'Osnabrück', 'Osnabrück',
       'Osterholz', 'Harz', 'Peine', 'Region Hannover',
       'Rotenburg', 'Salzgitter', 'Schaumburg', 'Stade',
       'ülzen', 'Vechta', 'Verden', 'Wesermarsch',
       'Wilhelmshaven', 'Wittmund', 'Wolfenbüttel',
       'Wolfsburg'], 'Brandenburg': ['Barnim', 'Brandenburg a.d.Havel', 'Cottbus',
       'Dahme-Spreewald', 'Elbe-Elster', 'Frankfurt',
       'Havelland', 'Märkisch-Oderland', 'Oberhavel',
       'Oberspreewald-Lausitz', 'Oder-Spree',
       'Ostprignitz-Ruppin', 'Potsdam', 'Potsdam-Mittelmark',
       'Prignitz', 'Spree-Neisse', 'Teltow-Fläming',
       'Uckermark'], 'Sachsen': ['Bautzen', 'Chemnitz', 'Dresden', 'Erzgebirgeis',
       'Görlitz', 'Leipzig', 'Leipzig', 'Meissen',
       'Mittelsachsen', 'Nordsachsen',
       'Sächsische Schweiz-Osterzgebirge', 'Vogtlandkreis',
       'Zwickau'], 'Hessen': ['Bergstrasse', 'Darmstadt', 'Darmstadt-Dieburg',
       'Frankfurt am Main', 'Fulda', 'Giessen', 'Gross-Gerau',
       'Hersfeld-Rotenburg', 'Hochtaunueis', 'Kassel',
       'Kassel', 'Lahn-Dill-Kreis', 'Limburg-Weilburg',
       'Main-Kinzig-Kreis', 'Main-Taunus-Kreis',
       'Marburg-Biedenkopf', 'Odenwaldkreis', 'Offenbach',
       'Offenbach', 'Rheingau-Taunus-Kreis',
       'Schwalm-Eder-Kreis', 'Vogelsbergkreis',
       'Waldeck-Frankenberg', 'Werra-Meissner-Kreis',
       'Wetteraukreis', 'Wiesbaden'], 'Berlin': ['Barnim'], 'Bremen': ['Bremen', 'Bremerhaven'], 'Schleswig-Holstein': ['Dithmarschen', 'Flensburg', 'Herzogtum Laünburg',
       'Kiel', 'Hof', 'Neumünster', 'Nordfriesland',
       'Ostholstein', 'Pinneberg', 'Plön',
       'Rendsburg-Eckernförde', 'Schleswig-Flensburg',
       'Segeberg', 'Steinburg', 'Stormarn'], 'Hamburg': ['Hamburg'], 'Mecklenburg-Vorpommern': ['Ludwigslust-Parchim', 'Mecklenburgische Seenplatte',
       'Nordwestmecklenburg', 'Rostock', 'Rostock',
       'Schwerin', 'Vorpommern-Greifswald', 'Vorpommern-Rügen'], 'Saarland': ['Merzig-Wadern', 'Neunkirchen', 'Saarlouis',
       'Saarpfalz-Kreis', 'Wesel', 'Stadtverband Saarbrücken'],
}

# # https://www.destatis.de/DE/Themen/Länder-Regionen/Regionales/Gemeindeverzeichnis/Administrativ/beschreibung-gebietseinheiten.pdf?__blob=publicationFile
RS = {
    '01': 'Schleswig-Holstein',
    '02': 'Hamburg',
    '03': 'Niedersachsen',
    '04': 'Bremen',
    '05': 'Nordrhein-Westfalen',
    '06': 'Hessen',
    '07': 'Rheinland-Pfalz',
    '08': 'Baden-Württemberg',
    '09': 'Bayern',
    '10': 'Saarland',
    '11': 'Berlin',
    '12': 'Brandenburg',
    '13': 'Mecklenburg-Vorpommern',
    '14': 'Sachsen',
    '15': 'Sachsen-Anhalt',
    '16': 'Thüringen'
}
choices_state=[
    'Baden-Württemberg',
    'Bayern',
    'Berlin',
    'Brandenburg',
    'Bremen',
    'Hamburg',
    'Hessen',
    'Mecklenburg-Vorpommern',
    'Niedersachsen',
    'Nordrhein-Westfalen',
    'Rheinland-Pfalz',
    'Saarland',
    'Sachsen',
    'Sachsen-Anhalt',
    'Schleswig-Holstein',
    'Thüringen'
]
choices_county=[
    'Alb-Donau-Kreis',
    'Biberach',
    'Böblingen','Bodenseekreis',
    'Breisgau-Hochschwarzwald',
    'Calw',
    'Emmendingen',
    'Enzkreis',
    'Esslingen',
    'Freudenstadt',
    'Göppingen',
    'Heidenheim',
    'Heilbronn',
    'Hohenlohekreis',
    'Karlsruhe',
    'Konstanz',
    'Lörrach',
    'Ludwigsburg',
    'Main-Tauber-Kreis',
    'Neckar-Odenwald-Kreis',
    'Ortenaukreis',
    'Ostalbkreis',
    'Rastatt',
    'Ravensburg',
    'Rems-Murr-Kreis',
    'Reutlingen',
    'Rhein-Neckar-Kreis',
    'Rottweil',
    'Schwäbisch Hall',
    'Schwarzwald-Baar-Kreis',
    'Sigmaringen',
    'Tübingen',
    'Tuttlingen',
    'Waldshut',
    'Zollernalbkreis',
    'Baden-Baden',
    'Freiburg i.Breisgau',
    'Heidelberg',
    'Heilbronn',
    'Karlsruhe',
    'Mannheim',
    'Pforzheim',
    'Stuttgart',
    'Ulm',
    'Aichach-Friedberg',
    'Altötting',
    'Amberg-Sulzbach',
    'Ansbach',
    'Aschaffenburg',
    'Augsburg',
    'Bad Kissingen',
    'Bad Tölz-Wolfratshausen',
    'Bamberg',
    'Bayreuth',
    'Berchtesgadener Land',
    'Cham',
    'Coburg',
    'Dachau',
    'Deggendorf',
    'Dillingen a.d.Donau',
    'Dingolfing-Landau',
    'Donau-Ries',
    'Ebersberg',
    'Eichstätt',
    'Erding',
    'Erlangen-Höchstadt',
    'Forchheim',
    'Freising',
    'Freyung-Grafenau',
    'Fürstenfeldbruck',
    'Fürth',
    'Garmisch-Partenkirchen',
    'Günzburg',
    'Hassberge',
    'Hof',
    'Kelheim',
    'Kitzingen',
    'Kronach',
    'Kulmbach',
    'Landsberg a.Lech',
    'Landshut',
    'Lichtenfels',
    'Lindau',
    'Main-Spessart',
    'Miesbach',
    'Miltenberg',
    'Mühldorf a.Inn',
    'München',
    'Neu-Ulm',
    'Neuburg-Schrobenhausen',
    'Neumarkt i.d.OPf.',
    'Neustadt a.d.Aisch-Bad Windsheim',
    'Neustadt a.d.Waldnaab',
    'Nürnberger Land',
    'Oberallgäu',
    'Ostallgäu',
    'Passau',
    'Pfaffenhofen a.d.Ilm',
    'Regen',
    'Regensburg',
    'Rhön-Grabfeld',
    'Rosenheim',
    'Roth',
    'Rottal-Inn',
    'Schwandorf',
    'Schweinfurt',
    'Starnberg',
    'Straubing-Bogen',
    'Tirschenreuth',
    'Traunstein',
    'Unterallgäu',
    'Weilheim-Schongau',
    'Weissenburg-Gunzenhausen',
    'Wunsiedel i.Fichtelgebirge',
    'Würzburg',
    'Amberg',
    'Ansbach',
    'Aschaffenburg',
    'Augsburg',
    'Bamberg',
    'Bayreuth',
    'Coburg',
    'Erlangen',
    'Fürth',
    'Hof',
    'Ingolstadt',
    'Kaufbeuren',
    'Kempten',
    'Landshut',
    'Memmingen',
    'München',
    'Nürnberg',
    'Passau',
    'Regensburg',
    'Rosenheim',
    'Schwabach',
    'Schweinfurt',
    'Straubing',
    'Weiden i.d.OPf.',
    'Würzburg',
    'Berlin Charlottenburg-Wilmersdorf',
    'Berlin Friedrichshain-Kreuzberg',
    'Berlin Lichtenberg',
    'Berlin Marzahn-Hellersdorf',
    'Berlin Mitte',
    'Berlin Neukölln',
    'Berlin Pankow',
    'Berlin Reinickendorf',
    'Berlin Spandau',
    'Berlin Steglitz-Zehlendorf',
    'Berlin Tempelhof-Schöneberg',
    'Berlin Treptow-Köpenick',
    'Barnim',
    'Dahme-Spreewald',
    'Elbe-Elster',
    'Havelland',
    'Märkisch-Oderland',
    'Oberhavel',
    'Oberspreewald-Lausitz',
    'Oder-Spree',
    'Ostprignitz-Ruppin',
    'Potsdam-Mittelmark',
    'Prignitz',
    'Spree-Neisse',
    'Teltow-Fläming',
    'Uckermark',
    'Brandenburg a.d.Havel',
    'Cottbus',
    'Frankfurt ',
    'Potsdam',
    'Bremen',
    'Bremerhaven',
    'Hamburg',
    'Bergstrasse',
    'Darmstadt-Dieburg',
    'Fulda',
    'Giessen',
    'Gross-Gerau',
    'Hersfeld-Rotenburg',
    'Hochtaunueis',
    'Kassel',
    'Lahn-Dill-Kreis',
    'Limburg-Weilburg',
    'Main-Kinzig-Kreis',
    'Main-Taunus-Kreis',
    'Marburg-Biedenkopf',
    'Odenwaldkreis',
    'Offenbach',
    'Rheingau-Taunus-Kreis',
    'Schwalm-Eder-Kreis',
    'Vogelsbergkreis',
    'Waldeck-Frankenberg',
    'Werra-Meissner-Kreis',
    'Wetteraukreis',
    'Darmstadt',
    'Frankfurt am Main',
    'Kassel',
    'Offenbach',
    'Wiesbaden',
    'Ludwigslust-Parchim',
    'Mecklenburgische Seenplatte',
    'Nordwestmecklenburg',
    'Rostock',
    'Vorpommern-Greifswald',
    'Vorpommern-Rügen',
    'Rostock',
    'Schwerin',
    'Ammerland',
    'Aurich',
    'Celle',
    'Cloppenburg',
    'Cuxhaven',
    'Diepholz',
    'Emsland',
    'Friesland',
    'Gifhorn',
    'Goslar',
    'Göttingen',
    'Grafschaft Bentheim',
    'Hameln-Pyrmont',
    'Harburg',
    'Heidekreis',
    'Helmstedt',
    'Hildesheim',
    'Holzminden',
    'Leer',
    'Lüchow-Dannenberg',
    'Lüneburg',
    'Nienburg',
    'Northeim',
    'Oldenburg',
    'Osnabrück',
    'Osterholz',
    'Peine',
    'Rotenburg',
    'Schaumburg',
    'Stade',
    'ülzen',
    'Vechta',
    'Verden',
    'Wesermarsch',
    'Wittmund',
    'Wolfenbüttel',
    'Region Hannover',
    'Braunschweig',
    'Delmenhorst',
    'Emden',
    'Oldenburg',
    'Osnabrück',
    'Salzgitter',
    'Wilhelmshaven',
    'Wolfsburg',
    'Borken',
    'Cösfeld',
    'Düren',
    'Ennepe-Ruhr-Kreis',
    'Eurchen',
    'Gütersloh',
    'Heinsberg',
    'Herford',
    'Hochsaürlandkreis',
    'Höxter',
    'Kleve',
    'Lippe',
    'Märkischer Kreis',
    'Mettmann',
    'Minden-Lübbecke',
    'Oberbergischer Kreis',
    'Olpe',
    'Paderborn',
    'Recklinghausen',
    'Rhein-Erft-Kreis',
    'Rhein-Kreis Neuss',
    'Rhein-Sieg-Kreis',
    'Rheinisch-Bergischer Kreis',
    'Siegen-Wittgenstein',
    'Söst',
    'Steinfurt',
    'Unna',
    'Viersen',
    'Warendorf',
    'Wesel',
    'Bielefeld',
    'Bochum',
    'Bonn',
    'Bottrop',
    'Dortmund',
    'Duisburg',
    'Düsseldorf',
    'Essen',
    'Gelsenkirchen',
    'Hagen',
    'Hamm',
    'Herne',
    'Köln',
    'Krefeld',
    'Leverkusen',
    'Mönchengladbach',
    'Mülheim a.d.Ruhr',
    'Münster',
    'Oberhausen',
    'Remscheid',
    'Solingen',
    'Wuppertal',
    'StadtRegion Aachen',
    'Ahrweiler',
    'Altenkirchen',
    'Alzey-Worms',
    'Bad Dürkheim',
    'Bad Kreuznach',
    'Bernkastel-Wittlich',
    'Birkenfeld',
    'Bitburg-Prüm',
    'Cochem-Zell',
    'Donnersbergkreis',
    'Germersheim',
    'Kaiserslautern',
    'Kusel',
    'Mainz-Bingen',
    'Mayen-Koblenz',
    'Neuwied',
    'Rhein-Hunsrück-Kreis',
    'Rhein-Lahn-Kreis',
    'Rhein-Pfalz-Kreis',
    'Südliche Weinstrasse',
    'Südwestpfalz',
    'Trier-Saarburg',
    'Vuneifel',
    'Westerwaldkreis',
    'Frankenthal',
    'Kaiserslautern',
    'Koblenz',
    'Landau i.d.Pfalz',
    'Ludwigshafen',
    'Mainz',
    'Neustadt a.d.Weinstrasse',
    'Pirmasens',
    'Speyer',
    'Trier',
    'Worms',
    'Zweibrücken',
    'Merzig-Wadern',
    'Neunkirchen',
    'Saarlouis',
    'Saarpfalz-Kreis',
    'Sankt Wendel',
    'Stadtverband Saarbrücken',
    'Bautzen',
    'Erzgebirgeis',
    'Görlitz',
    'Leipzig',
    'Meissen',
    'Mittelsachsen',
    'Nordsachsen',
    'Sächsische Schweiz-Osterzgebirge',
    'Vogtlandkreis',
    'Zwickau',
    'Chemnitz',
    'Dresden',
    'Leipzig',
    'Altmarkkreis Salzwedel',
    'Anhalt-Bitterfeld',
    'Börde',
    'Burgenlandkreis',
    'Harz',
    'Jerichower Land',
    'Mansfeld-Südharz',
    'Saalekreis',
    'Salzlandkreis',
    'Stendal',
    'Wittenberg',
    'Dessau-Rosslau',
    'Halle',
    'Magdeburg',
    'Dithmarschen',
    'Herzogtum Laünburg',
    'Nordfriesland',
    'Ostholstein',
    'Pinneberg',
    'Plön',
    'Rendsburg-Eckernförde',
    'Schleswig-Flensburg',
    'Segeberg',
    'Steinburg',
    'Stormarn',
    'Flensburg',
    'Kiel',
    'Lübeck',
    'Neumünster',
    'Altenburger Land',
    'Eichsfeld',
    'Gotha',
    'Greiz',
    'Hildburghausen',
    'Ilm-Kreis',
    'Kyffhäuserkreis',
    'Nordhausen',
    'Saale-Holzland-Kreis',
    'Saale-Orla-Kreis',
    'Saalfeld-Rudolstadt',
    'Schmalden-Meiningen',
    'Sömmerda',
    'Sonneberg',
    'Unstrut-Hainich-Kreis',
    'Wartburgkreis',
    'Weimarer Land',
    'Eisenach',
    'Erfurt',
    'Gera',
    'Jena',
    'Suhl',
    'Weimar'
]