name: Collect Data

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    name: Collect new data
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Collect data
        run: python -c 'from covid_charts import collect_data; collect_data.collect()'
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: EndBug/add-and-commit@v7
        with:
          author_name: Github actions
          branch: main
          message: Added data for ${{ steps.date.outputs.date }}
